mysite/urls.py
"""mysite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView # <--

from microdollars import views
from django.conf import settings # new
from django.urls import path, include # new
from django.conf.urls.static import static # new
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('', views.index, name='index'),
    path('profile', views.profile, name='profile'),
    path('lookup', views.lookup , name='lookup'),
    path('about', views.about, name='about'),
    path('leaderboard/', views.gamify, name='leaderboard'),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

microdollars/models.py
from django.db import models

from django.contrib.auth.models import User


class OrganizationModel(models.Model):
    organization_name = models.CharField(max_length=100)
    image = models.ImageField(upload_to="myimages",
                              default="/static/microdollars/missing.png")
    about_me = models.TextField(
        max_length=1000, default='INFO ON THIS ORGANIZATION')

    def __str__(self):
        return self.organization_name


# {% comment %}
# /***************************************************************************************
# *  REFERENCES
# *  Title: How to Implement Dependent/Chained Dropdown List with Django
# *  Author: Vitor Freitas
# *  Date: 1/29/18
# *  Code version: N/A
# *  URL: https://simpleisbetterthancomplex.com/tutorial/2018/01/29/how-to-implement-dependent-or-chained-dropdown-list-with-django.html
# *  Software License: Part of a tutorial
# *
# ***************************************************************************************/
# {% endcomment %}


class Donation(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL,
                             null=True, related_name='usernames', default=None)
    donateto = models.ForeignKey(
        OrganizationModel, on_delete=models.SET_NULL, null=True, verbose_name="Organization")
    amount = models.DecimalField(decimal_places=2, max_digits=10)
    comment = models.CharField(max_length=350, blank=True)
    models.CharField(max_length=350, blank=True)

    def convertToTuple(self, info):
        obj = info.objects.all()


class Search(models.Model):
    user_search = models.CharField(max_length=350, default="")

microdollars/forms.py
from allauth.account.forms import LoginForm
from django import forms
from django.utils.translation import gettext_lazy
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from microdollars.models import Donation, OrganizationModel, Search
from django.contrib.auth.models import User

class DonationForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['donateto'].queryset = OrganizationModel.objects.all()
        self.fields['donateto'].empty_label = None

    def clean_amount(self):
        data = self.cleaned_data['amount']
        if data <= 0:
            raise ValidationError("You can't donate a non-positive amount!")
        return data

    class Meta:
        model = Donation
        fields = ('donateto', 'amount', 'comment')
        widgets = {
            'donateto': forms.Select(attrs={'class': 'form-control donationitem'}),
            'amount': forms.NumberInput(attrs={'class': 'form-control donationitem'}),
            'comment': forms.TextInput(attrs={'class': 'form-control donationitem'}),
        }

        labels = {

            'donateto': gettext_lazy('Donate to'),
            'amount': gettext_lazy('Amount'),
            'comment': gettext_lazy('Comment'),

        }

class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'last_login', 'date_joined')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control forminput'}), 
            'email': forms.TextInput(attrs={'class': 'form-control forminput', 'readonly': 'readonly'}), 
            'first_name': forms.TextInput(attrs={'class': 'form-control forminput'}), 
            'last_name': forms.TextInput(attrs={'class': 'form-control forminput'}), 
            'last_login': forms.TextInput(attrs={'class': 'form-control forminput', 'readonly': 'readonly'}), 
            'date_joined': forms.TextInput(attrs={'class': 'form-control forminput', 'readonly': 'readonly'}),
        }
        labels = {
            'username': gettext_lazy('Username'),
            'email': gettext_lazy('Email'),
            'first_name': gettext_lazy('First name'),
            'last_name': gettext_lazy('Last name'),
            'last_login': gettext_lazy('Last login'),
            'date_joined': gettext_lazy('Date joined'),
        }
        help_texts = {
            'username': None,
            'email': None,
        }


class SearchForm(forms.ModelForm):
    class Meta:
        model = Search
        fields = ('user_search',)
        widgets = {
            'user_search': forms.TextInput(attrs={'class': 'form-control donationitem'})
        }
        labels = {
            'user_search': gettext_lazy("Input a username")
        }

    def clean_user_search(self):
        username = self.cleaned_data['user_search']
        try:
            uid = User.objects.get(username=username)
        except ObjectDoesNotExist:
            raise ValidationError(
                ('Username ' + username + ' does not exist'), code='noUserError')
        return username


class OrganizationForm(forms.ModelForm):
    class Meta:
        model = OrganizationModel
        fields = ('organization_name', 'about_me')
        widgets = {
            'organization_name': forms.TextInput(attrs={'class': 'form-control donationitem'}),
            'about_me': forms.TextInput(attrs={'class': 'form-control donationitem'}),
        }
        labels = {
            'organization_name': gettext_lazy('Organization'),
            'about_me': gettext_lazy('About this Organization'),
        }
        # def __unicode__


class CustomLoginForm(LoginForm):
    def __init__(self, *args, **kwargs):
        super(CustomLoginForm, self).__init__(*args, **kwargs)
        self.fields['login'].widget = forms.TextInput(
            attrs={'class': 'form-control'})
        self.fields['password'].widget = forms.PasswordInput(
            attrs={'class': 'form-control'})

microdollars/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from .models import Donation, OrganizationModel, Search
from .tables import DonationTable
from django.contrib.auth.models import User
from microdollars.forms import ProfileForm, DonationForm, SearchForm, Search
from django.core.exceptions import ObjectDoesNotExist
from django_tables2.config import RequestConfig
from collections import Counter
from django.contrib.auth.models import User
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib import messages
from collections import Counter
import statistics
# Create your views here.


def index(request):
    form = DonationForm(request.POST or None)
    if form.is_valid():
        tempForm = form.save(commit=False)
        if request.user and not request.user.is_anonymous:
            tempForm.user = request.user
        else:
            tempForm.user = None
        tempForm.save()
        messages.success(
            request, "Successfully completed transaction!")
        return redirect(reverse('index'))

    if request.user.is_anonymous:
        messages.warning(
            request, "You're not logged in, so your donation will be anonymous. It won't show up on leaderboards, or on any profile!")

    # generate string for top banner display
    banner = {'text': ""}
    if request.user.is_authenticated:
        # get total donation amount
        sum = 0
        try:
            for donation in Donation.objects.filter(user=request.user.id):
                sum += donation.amount
        except:
            pass
        text = ""
        if sum == 0:
            emoji = 128578
            tolevelup = 10
            text = "Your level is &#" + \
                str(emoji) + ", donate $" + \
                str(tolevelup) + " more to level up!"
        elif sum < 10:
            emoji = 128513
            tolevelup = 10 - sum
            text = "Your level is &#" + \
                str(emoji) + ", donate $" + \
                str(tolevelup) + " more to level up!"
        elif sum < 100:
            emoji = 129297
            tolevelup = 100 - sum
            text = "Your level is &#" + \
                str(emoji) + ", donate $" + \
                str(tolevelup) + " more to level up!"
        elif sum < 1000:
            emoji = 129321
            tolevelup = 1000 - sum
            text = "Your level is &#" + \
                str(emoji) + ", donate $" + \
                str(tolevelup) + " more to level up!"
        else:
            emoji = 128081
            text = "Your level is &#" + \
                str(emoji) + ", you are at the max level!"
        banner['text'] = text
    context = {
        'form': form,
        'donation_list': Donation.objects,
        'organizations': OrganizationModel.objects.all(),
        'banner': banner,
    }
    return render(request, "microdollars/index.html", context)


def profile(request):
    form = ProfileForm(request.POST or None, instance=request.user)
    message = ""
    if form.is_valid():
        form.save()
        message = '<div class="alert alert-success" role="alert">Successfully updated profile!</div>'
    context = {
        'form': form,
        'message': message,
    }
    return render(request, "microdollars/profile.html", context)


def usernameToUserDonations(username):
    try:
        uid = User.objects.get(username=username)
    except ObjectDoesNotExist:
        return None
    print("test")
    return Donation.objects.filter(user=uid)


def lookup(request):
    print("form")
    form = SearchForm(request.GET or None)
    donationTable = None
    data = None
    labels = None
    donationsEmpty = False
    average = None
    mode = None
    median = None
    username = None

    def calcDonationsPerOrg(username):
        userDonations = usernameToUserDonations(username)
        orgToTotalDonations = dict()
        for donation in userDonations:
            orgName = donation.donateto.organization_name
            orgToTotalDonations[orgName] = orgToTotalDonations.get(
                orgName, 0) + donation.amount
        return orgToTotalDonations

    def calcAvgDonationAmount(userDonations):
        print(userDonations)
        return round(statistics.mean(userDonations), 2)

    def calcModeAmount(userDonations):
        return max(userDonations, key=userDonations.count)

    def calcMedianAmount(userDonations):
        return statistics.median(userDonations)

    if form.is_valid():
        username = form.cleaned_data['user_search']
        donations = usernameToUserDonations(username)
        donationTable = DonationTable(donations)
        donationsEmpty = (donations.count() == 0)
        RequestConfig(request).configure(donationTable)

        if not donationsEmpty:
            # calc total donations
            orgToTotalDonations = calcDonationsPerOrg(username)
            data = [float(val)
                    for val in list(orgToTotalDonations.values())]
            labels = list(orgToTotalDonations.keys())
            donationsList = [d['amount'] for d in donations.values()]
            average = calcAvgDonationAmount(donationsList)
            mode = calcModeAmount(donationsList)
            median = calcMedianAmount(donationsList)
    context = {
        'form': form,
        'donationsEmpty':  donationsEmpty,
        'donationTable': donationTable,
        'data': data,
        'labels': labels,
        'average': average,
        'mode': mode,
        'median': median,
        'username': username,
    }
    return render(request, "microdollars/lookup.html", context)


def gamify(request):
    donations = None

    def usernameToUserDonations(username):
        try:
            uid = User.objects.get(username=username)
        except ObjectDoesNotExist:
            return None
        return Donation.objects.filter(user=uid)

    def exponential(user, donation):
        if(donation == 0):
            return (user, donation, 128578)
        elif(donation < 10):
            return (user, donation, 128513)
        elif(donation < 100):
            return (user, donation, 129297)
        elif(donation < 1000):
            return (user, donation, 129321)
        else:
            return (user, donation, 128081)

    def getAllDonations():
        userList = User.objects.all()
        sum = 0
        leaderboard = []
        for user in userList:
            getUserDonations = usernameToUserDonations(user.username)
            for donation in getUserDonations:
                sum += donation.amount
            leaderboard.append(exponential(user.username, sum))
            sum = 0
        return leaderboard

    def sortThis():
        return sorted(getAllDonations(), key=lambda x: x[1], reverse=True)

    def numberList(rankingslist):
        finallist = []
        i = 1
        for rankings in rankingslist:
            finallist.append((i, rankings[0], rankings[1], rankings[2]))
            i += 1
        return finallist

    context = {
        'leaderboard': numberList(sortThis()),
    }

    return render(request, "microdollars/leaderboard.html", context)


def about(request):
    return render(request, "microdollars/about.html")

microdollars/templates/microdollars/index.html
{% comment %}
/***************************************************************************************
*  REFERENCES
*  Title: In 5 mins: Set up Google login to sign up users on Django
*  Author: Zoe Chew
*  Date: 7/27/19
*  Code version: n/a
*  URL: https://medium.com/@whizzoe/in-5-mins-set-up-google-login-to-sign-up-users-on-django-e71d5c38f5d5
*  Software License: Not released under license, part of tutorial
*
***************************************************************************************/
{% endcomment %}
{% comment %}
/***************************************************************************************
*  REFERENCES
*  Title: PayPal Checkout Integration Guide
*  Author: PayPal
*  Date: 2020
*  Code version: n/a
*  URL: https://developer.paypal.com/docs/archive/checkout/integrate/
*  Software License: Not released under license, part of tutorial
*
***************************************************************************************/
{% endcomment %}
{% load socialaccount %}
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>MicroDollars</title>

    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'microdollars/style.css' %}">
    <!-- favicon.ico -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'microdollars/favicon.ico' %}"/>

    <!-- JS, Popper.js, and jQuery for Bootstrap-->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    
    <script src="https://www.paypal.com/sdk/js?client-id=AWylIyJKwiuyxCjW6IY-eF0WTFG_IWCBGJXxUhBtV351q8tz7KgLUoGy6rKt73Y5PY9t1UYCcekVf_lz"></script>

  </head>
  <body class="bg-darkerlight">
    <!-- START HEADER -->
    <!-- First navbar row -->
    <div class="navbar navbar-default navbar-expand-md navbar-light bg-darkerlight">
      <div class="container">
        <a href="#" class="h1 navbar-brand nomargin">MicroDollars</a>
        {% if user.is_authenticated %}
          <!-- Sign out button -->
          <a class="btn btn-outline-danger pull-right" role="button" href="/accounts/logout/">Logout</a>
        {% else %}
          <!-- Log in/Sign up button -->
          <a class="btn btn-outline-success pull-right" role="button" href="{% provider_login_url 'google' %}">Log in/Sign up with Google</a>
        {% endif %}
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </div>
    <!-- Second navbar row -->
    <div class="navbar navbar-default navbar-expand-md navbar-dark bg-success">
      <div class="container">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">Home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/about">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/lookup">User Lookup</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/leaderboard">Leaderboard</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="/profile">My Profile</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
    <div class="navbar navbar-expand-md bg-light">
      <div class="container">
        {% if user.is_authenticated %}
        <p id="username" class="h1 navbar-brand nomargin">Welcome, {{ user.username }}! {{ banner.text|safe }}</p>
        {% else %}
        <p id="username" class="h1 navbar-brand nomargin">Not Logged In</p>
        {% endif %}
      </div>
    </div>
    <!-- STOP HEADER -->

    <!-- START PAGE CONTENT -->
    <div id="maincontent" class="container">

      <br>
      <div class="row">
        <div class="col-md-12 bg-light padding rounded orglist">
            {% for org in organizations %}
              <div class="orgcard-outer">
                <div class="orgcard-inner" id="{{ org.organization_name }}" onclick="changeOrgDropdown(this)"> <!-- background org image -->
                  <div class="orgcard-bg" style="background-image: url({{ org.image.url }});"></div>
                  <img class="orgcard-img" src="{{ org.image.url }}">
                  <h3 style="text-align: center;">{{ org.organization_name }}</h3>
                  <h6 style="padding: 4px;">{{ org.about_me }}</h6>
                </div>
              </div>
            {% endfor %}

        </div>
      </div>

      <br>
      <div class="row">
        <div class="col-md-12 bg-light padding rounded">
          <div class="row justify-content-center">
            <div class="col-sm-12 col-md-8">
            {% if messages %}
                <div class="messages">
                    {% for message in messages %}
                        <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{message}}</div>
                    {% endfor %}
                </div>
            {% endif %}
              {{ message|safe }}
              <form id="donationform" method="POST">
                <div id="empty_error" class="hidden alert alert-danger">Amount can't be empty!</div>
                <div id="amount_error" class="hidden alert alert-danger">Amount must be positive!</div>
                <div id="decimal_error" class="hidden alert alert-danger">Too many decimals! Please limit to 1 cent increments.</div>
                {% csrf_token %}
                {{ form }}
              </form>
            </div>
          </div>
          <div class="row justify-content-center">
            <div class="col-sm-12 col-md-8 col-lg-4">
              <div id="paypal-button-container"></div>
            </div>
          </div>
          <script>
              function getDecimals(val) {
                var text = val.toString();
                var index = text.indexOf(".");
                var decimals = 0;
                if(index != -1){
                  decimals = text.length - index - 1;
                }
                else{
                  decimals = 0;
                }
                console.log(decimals)
                return decimals
              }
              paypal.Buttons({
                fundingSource: paypal.FUNDING.PAYPAL,
                style: {
                  layout:  'horizontal'
                },
                onInit: function(data, actions) {
                  // Disable the buttons
                  actions.disable();
                  console.log("init!")
                  // Listen for changes to the checkbox
                  document.querySelector('#id_amount')
                    .addEventListener('input', function(event) {
                      // Enable or disable the button when it is checked or unchecked
                      console.log("listening")
                      console.log(getDecimals(event.target.value))
                      if (event.target.value > 0 && getDecimals(event.target.value) <= 2) {
                        console.log("enabled")
                        actions.enable();
                      } else {
                        actions.disable();
                      }
                    });
                },
                onClick: function() {
                  var amount = document.querySelector('#id_amount').value

                  document.querySelector('#empty_error').classList.add('hidden');
                  document.querySelector('#amount_error').classList.add('hidden');
                  document.querySelector('#decimal_error').classList.add('hidden');

                  if(amount == "") {
                    document.querySelector('#empty_error').classList.remove('hidden');
                  }
                  else{
                    if (amount <= 0) {
                    document.querySelector('#amount_error').classList.remove('hidden');
                    }
                    if (amount != ""  && getDecimals(amount) > 2) {
                      document.querySelector('#decimal_error').classList.remove('hidden');
                    }
                  }
                },
                createOrder: function(data, actions) {
                  // This function sets up the details of the transaction, including the amount and line item details.
                  return actions.order.create({
                    purchase_units: [{
                      amount: {
                        value: document.getElementById("id_amount").value
                      }
                    }],
                    application_context: {
                      shipping_preference: "NO_SHIPPING",
                    },
                  });
                },
                onApprove: function(data, actions) {
                  // This function captures the funds from the transaction.
                  return actions.order.capture().then(function(details) {
                    // This function shows a transaction success message to your buyer.
                    document.getElementById("donationform").submit();
                  });
                }
              }).render('#paypal-button-container');
              // This function displays Smart Payment Buttons on your web page.
          </script>
        </div>
      </div>
      <br>
    </div>
    <!-- STOP PAGE CONTENT -->

    <!-- START FOOTER -->
    <div class="spacer"></div>
    <footer class="font-small bg-darkblue text-darkerlight">
      <div class="footer-copyright text-center py-3">
        2020
        <b>2JV Team</b> (John Kim, Jami Park, Vinay Garimella, Vasil Zhigilei)
      </div>
    </footer>
    <!-- STOP FOOTER -->

    <script>
      function changeOrgDropdown(div) {
        var id = div.id; // get org name from clicked card id
        var dropdown = document.getElementById("id_donateto") // get dropdown
        var optionsLength = dropdown.options.length;
        for (var i = 0; i < optionsLength; i++){
          if (dropdown.options[i].text == id){
            dropdown.options[i].selected = true;
            break;
          }
        }
      }
    </script>
  </body>
</html>

microdollars/templates/microdollars/profile.html
{% comment %}
/***************************************************************************************
*  REFERENCES
*  Title: In 5 mins: Set up Google login to sign up users on Django
*  Author: Zoe Chew
*  Date: 7/27/19
*  Code version: n/a
*  URL: https://medium.com/@whizzoe/in-5-mins-set-up-google-login-to-sign-up-users-on-django-e71d5c38f5d5
*  Software License: Not released under license, part of tutorial
*
***************************************************************************************/
{% endcomment %}

{% load socialaccount %}
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>MicroDollars &ndash; Profile</title>

    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'microdollars/style.css' %}">
    <!-- favicon.ico -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'microdollars/favicon.ico' %}"/>
    
    <!-- JS, Popper.js, and jQuery for Bootstrap-->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </head>
  <body class="bg-darkerlight">
    <!-- START HEADER -->
    <!-- First navbar row -->
    <div class="navbar navbar-default navbar-expand-md navbar-light bg-darkerlight">
      <div class="container">
        <a href="#" class="h1 navbar-brand nomargin">MicroDollars</a>
        {% if user.is_authenticated %}
          <!-- Sign out button -->
          <a class="btn btn-outline-danger pull-right" role="button" href="/accounts/logout/">Logout</a>
        {% else %}
          <!-- Log in/Sign up button -->
          <a class="btn btn-outline-success pull-right" role="button" href="{% provider_login_url 'google' %}">Log in/Sign up with Google</a>
        {% endif %}
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </div>
    <!-- Second navbar row -->
    <div class="navbar navbar-default navbar-expand-md navbar-dark bg-success">
      <div class="container">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/about">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/lookup">User Lookup</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/leaderboard">Leaderboard</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link" href="/profile">My Profile<span class="sr-only">(current)</span></a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
    <div class="navbar navbar-expand-md bg-light">
    </div>
    <!-- STOP HEADER -->

    <!-- START PAGE CONTENT -->
    <div id="maincontent" class="container">
        <br>
        <div class="row">
            <div class="col-md-8 bg-light padding rounded" style="margin-left: auto; margin-right: auto; padding: 2%;">
                {{ message|safe }}
                <form id="profileform" method="POST">
                    {% csrf_token %}
                    {{ form }}
                    <br>
                    <button type="submit" class="btn btn-success">Update Profile</button>
                </form>
            </div>
        </div>
        <br>
    </div>
    <!-- STOP PAGE CONTENT -->

    <!-- START FOOTER -->
    <div class="spacer"></div>
    <footer class="font-small bg-darkblue text-darkerlight">
      <div class="footer-copyright text-center py-3">
        2020
        <b>2JV Team</b> (John Kim, Jami Park, Vinay Garimella, Vasil Zhigilei)
      </div>
    </footer>
    <!-- STOP FOOTER -->

  </body>
</html>